### ISSUE TITLE
Sort functions alphabetically

### ISSUE THREAD

**Issue by datenreisender** [alexbepple/ramda-dash-docset#10]
On http://ramdajs.com/docs/ all functions are sorted alphabetically: The first three functions are `__`, `add` and `addIndex`. In the docset the functions are first grouped by category, making the first two functions `__` and `addIndex`, while `add` comes a lot later (together with all functions belong to the category Math).

It would be nice, if the functions in the docset are in the same order as the functions on the website.

**Comment by alexbepple** [comment]
First, some explanation for the current behavior might be in order.

I changed the order of the entries in order to be able to discover the functions of one category by scrolling. On http://ramdajs.com/docs/ it's not even obvious how to find all the functions that belong to one category. (You have to type the category name in the search box.) If you need the functions in alphabetic order, you can expand the Dash item "Functions":
<img width="243" alt="screen shot 2016-08-19 at 19 24 26" src="https://cloud.githubusercontent.com/assets/159355/17818161/93017ca4-6642-11e6-890b-fd0302746167.png">

So, what exactly is your need behind entries being sorted alphabetically? And do you have any suggestions as to how to discover functions within same category, if the entries were sorted alphabetically?

**Comment by alexbepple** [comment]
@datenreisender, may I close the issue?
